### ISSUE TITLE
Android Things Community Submission

### ISSUE THREAD

**Issue by devunwired** [Sensirion/android-things#6]
Thank you for submitting to the Android Things community drivers index. We are reviewing this submission now and will provide any additional requests for information here.

**Comment by devunwired** [comment]
Metadata needs a small fix, published #7 to address.

**Comment by chjaeggi** [comment]
@devunwired Thanks for reviewing it! Appreciate it. #7 has been merged to master

**Comment by devunwired** [comment]
The driver submission is now live in the community index:
https://androidthings.withgoogle.com/#!/drivers/Sensirion_android-things-sht3x
